 const catagories = [
    "---Select Category---",
    "Caltex - Passenger Car Motor Oils",
    "Lanka - Petrol Engine Oils",
    "Caltex - Heavy Duty Diesel Engine Oils",
    "Lanka - Diesel Engine Oils",
    "Caltex - Powershift Transmission Fluid",
    "Lanka - API GL-5 type Automotive Manual Gear Oils",
    "Caltex - Extreme Pressure API GL5/API MT-1 type Automotive Gear Oils",
    "Caltex - API GL4 type Automotive Manual Gear Oils",
    "Lanka - API GL-4 type Automotive Gear Oils",
    "Caltex - Two Stroke Engine Oils",
    "Caltex - Two Stroke Outboard Engine Oils",
    "Caltex - Four Stroke Motor Cycle Engine Oil",
    "Caltex - Industrial Gear Lubricants",
    "Caltex - Turbine Oils",
    "Caltex - Compressor Oils",
    "Caltex - Metal Working Fluids (Ready to use)",
    "Caltex - Metal Working Fluids (Water soluble)",
    "Caltex - Straight Mineral Circulation System Oil",
    "Lanka - Pneumatic Tool Lubricants",
    "Caltex - Automotive and Industrial Grease",
    "Caltex - Heat Transfer Oils",
    "Caltex - Open Gears",
    "Brake & Clutch Fluids",
    "Caltex - Automatic Transmision / Power Steering / Fork Lubricant",
    "Caltex - Automatic Transmision Fluid",
    "Caltex - Multifunctional Tractor Fluid",
    "Caltex - Coolants",
    "Caltex - Anti-wear Hydraulic Fluids",
    "Others"
  ];
  export default catagories